pkvm: x86: Fix "error: redefinition of 'kvm_get_apic_mode'"
Fix compilation failure after commit 2356acd8aa1d ("KVM: x86: Get
vcpu->arch.apic_base directly and drop kvm_get_apic_base()") and
commit 9d5034a35c3a ("KVM: x86: Inline kvm_get_apic_mode() in lapic.h")
which make pKVM's versions of these functions redundant.

Signed-off-by: Dmytro Maluka <dmaluka@google.com>